repos:
  - repo: local
    hooks:
      - id: collect-stat
        name: Collect Statistics
        entry: cargo run --bin collect-stat
        language: system
        pass_filenames: false
        stages: [commit]
